apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: osc-board-skaffold
  # labels: {}
  # annotations: {}
build:
  local:
    push: true
  artifacts:
    - image: docker.io/mirrorkyh/osc-board-api  # 빌드 이미지
      jib:
        args:
          - -DskipTests
        fromImage: docker.io/library/openjdk:11.0.11-jre  # Maven Plugin, 도커 이미지 생성
deploy:
   kubectl:
     manifests:
       - k8s/osc-board-api.yaml
   kustomize:
     paths:
       - k8s/base
