# MySQL8 설정
spring:
  datasource :
    driver-class-name : com.mysql.cj.jdbc.Driver
   # local Mysql
    url: jdbc:mysql://localhost:3306/oscboard?serverTimezone=Asia/Seoul
    username: root
    password: 3642
