#############
### 공통
##############

#spring:
#  profiles:
#    active: dev

# local Mysql // mysql 8 버전은 외부에서 붙이는 방법 따로있다.
# kubectl portforward로 빼면 localhost:3306으로 붙을 수 있다.
# DB는 도커-컴포즈로 설치, k8s 금지
# local Mysql // mysql 8 버전은 외부에서 붙이는 방법 따로있다.// kubectl portforward로 빼면 localhost:3306으로 붙을 수 있다.
# DB는 도커-컴포즈로 설치, k8s 금지


#로컬(kubernetes)에서 돌릴 때
#  profiles:
#    active: k8s
# MySQL8 설정
spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://host.docker.internal:3306/oscboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # 아래처럼 로칼 호스트 쓰면 k8s로 띄웠을 때 로컬의 띄운 도커 mysql을 못봐
#    url: jdbc:mysql://localhost:3306/oscboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # k3d 환경에서 기동
    url: jdbc:mysql://host.k3d.internal:3306/oscboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1q2w3e4r


# 콘솔에 SQL 출력 여부
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
# hibernate 설정
    database : mysql
    hibernate.ddl-auto : update
    hibernate.naming.strategy : org.hibernate.cfg.ImprovedNamingStrategy
    hibernate.naming.physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl : false
    properties.hibernate.format_sql : true
    properties.hibernate.enable_lazy_load_no_trans : true

# springdoc config

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true

