# MySQL8 설정


    # AWS DB 연결용
    #    url: ENC(TNWd0a695QHo3kVGfM38nx092Hx/u1n8TyDyNgP/WTWQ0h3h+HTV299JgpKKVlZn8f/NVwnXmQVN64da81lE4EGXv9qHgCRtj9/dhRlpFF+VtA+Ks8imNcaBXt5KThb0JqQuAOcoPZ4D7I+aohcWQuE1IJ5mOePolvCOMLxhYSKGn++77jdjsYwADAMWHXbZeRWoOI/CbLM=)
    #    username: ENC(mNmhKjCACY10khaXSzlDPw==)
    #    password: ENC(s45rHrvYh3PvvjP1mOfxszoDaiaqwDM3)
