apiVersion: apps/green
kind: Deployment
metadata:
  name: board-api
  namespace: api
spec:
  selector:
    matchLabels:
      app: board-api
  template:
    metadata:
      labels:
        app: board-api
    spec:
      containers:
        - name: board-api
          image: registry.a.ocp.local:5000/openshift4/hwan-api:v0.3
          ports:
            - name: http
              containerPort: 8080
