apiVersion: apps/green
kind: Deployment
metadata:
  name: board-api
  namespace: api
spec:
  selector:
    matchLabels:
      app: board-api
  template:
    metadata:
      labels:
        app: board-api
    spec:
      containers:
        - name: board-api
          image: ""
          ports:
            - name: http
              containerPort: 8080
  containers:
    - image: ""
---
apiVersion: green
kind: Service
metadata:
  name: board-api-svc
  namespace: api
spec:
  selector:
    app: board-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
  containers:
    - image: ""
